/**
 * Promo poster COMPOSER — assembles the final 1080×1350 creative with sharp:
 *
 *   Pollinations AI background (or procedural gradient fallback)
 *     + sharp hero photo (EXISTING product/model render, never regenerated)
 *     + clean offer block: ALL SAREES / ₹199 / FLAT
 *     + compact selling points + SHOP NOW pill + brand + factual footer
 *
 * HARD RULES: text is NEVER generated by the image model; the price string is
 * rendered exactly as stored in the campaign constants; the hero image is an
 * EXISTING render (Rule 6 — no regeneration).
 */
import "server-only";
import sharp from "sharp";
import { SITE } from "@/lib/site";
import {
  POSTER,
  POSTER_PALETTES,
  buildPosterGeometry,
  type PosterPalette,
  type PosterText,
} from "@/lib/marketing/promo/poster-card";
import { generateImageFromText } from "@/lib/marketing/pollinations";

/** XML-escape for SVG text nodes. */
function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const DISPLAY_STACK = "Arial, 'Helvetica Neue', Helvetica, sans-serif";
const SCRIPT_STACK = "Segoe Script, 'Comic Sans MS', 'Brush Script MT', cursive";
const BODY_STACK = "'Segoe UI', Arial, sans-serif";
const CANVAS = { width: POSTER.width, height: POSTER.height } as const;

type PosterVariant = {
  name: string;
  palette?: string;
  bgStyle: "terracotta" | "sale-yellow" | "cream-botanical" | "dark-luxe" | "rose-fashion" | "blue-gold";
  fontStyle: "bold" | "serif" | "fashion" | "condensed" | "classic" | "clean";
  hero: { x: number; y: number; w: number; h: number; radius: number };
  textX: number;
  brandY: number;
  offerY: number;
  pointsY: number;
  ctaY: number;
  footerY: number;
  offerStyle: "stacked" | "badge" | "editorial" | "compact";
  imageTreatment: "panel" | "edge" | "arch" | "circle";
};

const POSTER_VARIANTS: PosterVariant[] = [
  {
    name: "split-premium",
    bgStyle: "terracotta",
    fontStyle: "serif",
    palette: "TERRACOTTA_EDITORIAL",
    hero: { x: 492, y: 188, w: 548, h: 1058, radius: 34 },
    textX: 64,
    brandY: 48,
    offerY: 292,
    pointsY: 760,
    ctaY: 1018,
    footerY: 1276,
    offerStyle: "stacked",
    imageTreatment: "panel",
  },
  {
    name: "reel-bold",
    bgStyle: "sale-yellow",
    fontStyle: "bold",
    palette: "SALE_YELLOW",
    hero: { x: 514, y: 0, w: 566, h: 1350, radius: 0 },
    textX: 54,
    brandY: 50,
    offerY: 310,
    pointsY: 742,
    ctaY: 996,
    footerY: 1276,
    offerStyle: "compact",
    imageTreatment: "edge",
  },
  {
    name: "fashion-editorial",
    bgStyle: "cream-botanical",
    fontStyle: "fashion",
    palette: "CREAM_BOTANICAL",
    hero: { x: 466, y: 154, w: 520, h: 1048, radius: 260 },
    textX: 58,
    brandY: 58,
    offerY: 314,
    pointsY: 846,
    ctaY: 1042,
    footerY: 1278,
    offerStyle: "editorial",
    imageTreatment: "arch",
  },
  {
    name: "offer-badge",
    bgStyle: "rose-fashion",
    fontStyle: "condensed",
    palette: "ROSE_FASHION",
    hero: { x: 430, y: 244, w: 610, h: 914, radius: 28 },
    textX: 66,
    brandY: 56,
    offerY: 286,
    pointsY: 806,
    ctaY: 1018,
    footerY: 1276,
    offerStyle: "badge",
    imageTreatment: "panel",
  },
  {
    name: "catalogue-luxe",
    bgStyle: "dark-luxe",
    fontStyle: "classic",
    palette: "DARK_LUXE",
    hero: { x: 520, y: 138, w: 456, h: 1060, radius: 10 },
    textX: 62,
    brandY: 64,
    offerY: 328,
    pointsY: 790,
    ctaY: 1010,
    footerY: 1276,
    offerStyle: "stacked",
    imageTreatment: "panel",
  },
  {
    name: "soft-summer",
    bgStyle: "blue-gold",
    fontStyle: "clean",
    palette: "BLUE_GOLD_LUXE",
    hero: { x: 488, y: 178, w: 534, h: 1018, radius: 267 },
    textX: 62,
    brandY: 56,
    offerY: 318,
    pointsY: 824,
    ctaY: 1034,
    footerY: 1276,
    offerStyle: "editorial",
    imageTreatment: "circle",
  },
];

function posterVariant(seed = 0): PosterVariant {
  const i = Math.abs(Math.trunc(seed)) % POSTER_VARIANTS.length;
  return POSTER_VARIANTS[i] ?? POSTER_VARIANTS[0];
}

interface PosterFonts {
  display: string;
  script: string;
  body: string;
}

function fontsFor(style: PosterVariant["fontStyle"]): PosterFonts {
  switch (style) {
    case "serif":
      return {
        display: "Georgia, 'Times New Roman', serif",
        script: "Georgia, 'Times New Roman', serif",
        body: "'Segoe UI', Arial, sans-serif",
      };
    case "fashion":
      return {
        display: "'Bodoni 72', Didot, Georgia, serif",
        script: "Segoe Script, 'Brush Script MT', cursive",
        body: "Trebuchet MS, 'Segoe UI', sans-serif",
      };
    case "condensed":
      return {
        display: "'Arial Narrow', Impact, Arial, sans-serif",
        script: "'Brush Script MT', 'Segoe Script', cursive",
        body: "'Arial Narrow', Arial, sans-serif",
      };
    case "classic":
      return {
        display: "Garamond, Georgia, 'Times New Roman', serif",
        script: "Georgia, 'Times New Roman', serif",
        body: "Verdana, 'Segoe UI', sans-serif",
      };
    case "clean":
      return {
        display: "Trebuchet MS, 'Segoe UI', Arial, sans-serif",
        script: "Segoe Script, 'Brush Script MT', cursive",
        body: "'Segoe UI', Arial, sans-serif",
      };
    default:
      return { display: DISPLAY_STACK, script: SCRIPT_STACK, body: BODY_STACK };
  }
}

/** Marquee brush-banner with hand-painted edges (spikes + white underlay). */
function bannerSvg(w: number, h: number, skew: number, fill: string, deep: string): Buffer {
  const spikes = Array.from({ length: 7 }, (_, i) => {
    const x = 40 + i * ((w - 80) / 6);
    const spikeW = 46 + (i % 3) * 26;
    const spikeH = 22 + (i % 2) * 14;
    return `<rect x="${x}" y="${h - spikeH}" width="${spikeW}" height="${spikeH}" fill="${fill}" transform="skewX(${skew})"/>`;
  }).join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h + 40}">
    <g transform="skewX(${skew})">
      <rect x="18" y="14" width="${w}" height="${h}" fill="#ffffff" opacity="0.9"/>
      <rect x="0" y="0" width="${w}" height="${h}" fill="${fill}"/>
      <rect x="0" y="${h - 52}" width="${w}" height="52" fill="${deep}"/>
      ${spikes}
    </g>
  </svg>`;
  return Buffer.from(svg, "utf8");
}

/** Quote bubble with price + FLAT, tilted like the reference poster. */
function priceBubbleSvg(price: string, flat: string, fill: string, textFill: string): Buffer {
  const w = 470;
  const h = 300;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
    <g transform="rotate(-3 ${w / 2} ${h / 2})">
      <path d="M 30 40 Q 10 40 10 70 L 10 200 Q 10 230 40 230 L 60 230 L 30 285 L 105 230 L ${w - 40} 230 Q ${w - 10} 230 ${w - 10} 200 L ${w - 10} 70 Q ${w - 10} 40 ${w - 40} 40 Z"
        fill="${fill}" stroke="#ffffff" stroke-width="10"/>
      <text x="${w / 2}" y="150" text-anchor="middle" font-family="${DISPLAY_STACK}" font-weight="900" font-size="150" fill="${textFill}">${esc(price)}</text>
      <text x="${w / 2}" y="212" text-anchor="middle" font-family="${SCRIPT_STACK}" font-size="54" fill="${textFill}">${esc(flat)}</text>
    </g>
  </svg>`;
  return Buffer.from(svg, "utf8");
}

/** Selling-point rows: pale pill + dark check circle + wrapped label. */
function pointsSvg(
  items: string[],
  palette: PosterPalette,
  maxWidth: number,
  fonts: PosterFonts,
  variant: PosterVariant,
): { svg: Buffer; height: number } {
  const size = POSTER.pointsSize;
  const pillH = variant.bgStyle === "dark-luxe" ? 54 : 46;
  const gap = variant.bgStyle === "cream-botanical" ? 16 : 12;
  const heights: string[] = [];
  let y = pillH / 2 + 8;
  const rows: string[] = [];
  for (const item of items.slice(0, 3)) {
    let label = item;
    let width = Math.round(label.length * size * 0.56);
    if (width > maxWidth - 70) {
      label = `${label.slice(0, Math.max(8, Math.floor((maxWidth - 70) / (size * 0.56)) - 1))}…`;
      width = Math.round(label.length * size * 0.56);
    }
    const fontW = Math.round(label.length * size * 0.58);
    const scale = width > fontW ? 1 : fontW / Math.max(width, 1);
    const rowW = Math.max(width + 60, 120);
    const luxe = variant.bgStyle === "dark-luxe";
    const botanical = variant.bgStyle === "cream-botanical";
    const fill = luxe ? palette.price : palette.chipBg;
    const text = luxe ? palette.ctaText : botanical ? palette.bannerDeep : palette.chipText;
    const mark = botanical ? palette.bannerDeep : palette.banner;
    rows.push(
      `<g transform="translate(0 ${y})">` +
        (botanical
          ? `<line x1="0" y1="0" x2="${rowW}" y2="0" stroke="#${mark}" stroke-width="2" opacity="0.35"/>`
          : `<rect x="0" y="${-pillH / 2}" width="${rowW}" height="${pillH}" rx="${luxe ? 8 : pillH / 2}" fill="#${fill}" opacity="${luxe ? 0.88 : 0.92}"/>`) +
        `<circle cx="26" cy="0" r="${botanical ? 10 : 14}" fill="#${mark}"/>` +
        `<path d="M 19 0 L 24 6 L 34 -6" stroke="#${botanical ? palette.soft : palette.chipBg}" stroke-width="4.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>` +
        `<text x="50" y="${size * 0.36}" font-family="${fonts.body}" font-weight="700" font-size="${size}" fill="#${text}">${esc(label)}</text>` +
        `</g>`,
    );
    heights.push("");
    y += pillH + gap;
    void scale;
  }
  const total = y - gap + pillH / 2;
  return { svg: Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${maxWidth}" height="${total}">${rows.join("")}</svg>`, "utf8"), height: total };
}

function imageMask(w: number, h: number, r: number, treatment: PosterVariant["imageTreatment"]): Buffer {
  const shape =
    treatment === "arch"
      ? `<path d="M ${r} ${h} L ${w - r} ${h} Q ${w} ${h} ${w} ${h - r} L ${w} ${w / 2} Q ${w} 0 ${w / 2} 0 Q 0 0 0 ${w / 2} L 0 ${h - r} Q 0 ${h} ${r} ${h} Z" fill="#ffffff"/>`
      : treatment === "circle"
        ? `<ellipse cx="${w / 2}" cy="${h / 2}" rx="${w / 2}" ry="${h / 2}" fill="#ffffff"/>`
        : `<rect x="0" y="0" width="${w}" height="${h}" rx="${r}" fill="#ffffff"/>`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
    ${shape}
  </svg>`;
  return Buffer.from(svg, "utf8");
}

function offerBlockSvg(
  text: PosterText,
  palette: PosterPalette,
  style: PosterVariant["offerStyle"],
  fonts: PosterFonts,
): Buffer {
  const price = `₹${text.price}`;
  if (style === "badge") {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="430" height="468">
      <defs><filter id="shadow"><feDropShadow dx="0" dy="8" stdDeviation="5" flood-color="#3a130d" flood-opacity="0.24"/></filter></defs>
      <path d="M215 12 C298 12 366 54 396 120 C428 190 408 280 356 350 C312 410 260 450 215 450 C170 450 118 410 74 350 C22 280 2 190 34 120 C64 54 132 12 215 12Z" fill="#${palette.banner}" opacity="0.96" filter="url(#shadow)"/>
      <text x="215" y="116" text-anchor="middle" font-family="${fonts.display}" font-weight="900" font-size="40" fill="#${palette.ink}">${esc(text.offer)}</text>
      <text x="215" y="268" text-anchor="middle" font-family="${fonts.display}" font-weight="900" font-size="144" fill="#${palette.price}">${esc(price)}</text>
      <text x="215" y="330" text-anchor="middle" font-family="${fonts.body}" font-weight="900" font-size="42" letter-spacing="5" fill="#${palette.ink}">${esc(text.flatLabel)}</text>
    </svg>`;
    return Buffer.from(svg, "utf8");
  }
  if (style === "editorial") {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="510" height="430">
      <defs><filter id="shadow"><feDropShadow dx="0" dy="7" stdDeviation="3" flood-color="#2d1009" flood-opacity="0.22"/></filter></defs>
      <text x="0" y="72" font-family="${fonts.script}" font-size="72" fill="#${palette.ink}">${esc("Traditional")}</text>
      <text x="0" y="150" font-family="${fonts.display}" font-weight="900" font-size="68" fill="#${palette.ink}">${esc("SAREES")}</text>
      <text x="0" y="222" font-family="${fonts.body}" font-weight="700" font-size="30" fill="#${palette.soft}">${esc(text.offer)} AT</text>
      <text x="0" y="360" font-family="${fonts.display}" font-weight="900" font-size="158" fill="#${palette.price}" filter="url(#shadow)">${esc(price)}</text>
      <text x="16" y="416" font-family="${fonts.body}" font-weight="900" font-size="38" letter-spacing="5" fill="#${palette.ink}">${esc(text.flatLabel)}</text>
    </svg>`;
    return Buffer.from(svg, "utf8");
  }
  const offerSize = style === "compact" ? 52 : 56;
  const priceSize = style === "compact" ? 172 : 184;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="520" height="430">
    <defs>
      <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
        <feDropShadow dx="0" dy="8" stdDeviation="4" flood-color="#3a130d" flood-opacity="0.28"/>
      </filter>
    </defs>
    <text x="0" y="62" font-family="${fonts.display}" font-weight="900" font-style="italic" font-size="${offerSize}" fill="#${palette.ink}" letter-spacing="1">${esc(text.offer)}</text>
    <line x1="0" y1="104" x2="128" y2="104" stroke="#${palette.soft}" stroke-width="4" opacity="0.9"/>
    <text x="154" y="116" font-family="${fonts.body}" font-weight="700" font-size="34" fill="#${palette.soft}">AT</text>
    <line x1="218" y1="104" x2="380" y2="104" stroke="#${palette.soft}" stroke-width="4" opacity="0.9"/>
    <text x="0" y="278" font-family="${fonts.display}" font-weight="900" font-size="${priceSize}" fill="#${palette.price}" filter="url(#shadow)">${esc(price)}</text>
    <text x="12" y="352" font-family="${fonts.display}" font-weight="900" font-size="48" fill="#${palette.ink}" letter-spacing="6">${esc(text.flatLabel)}</text>
  </svg>`;
  return Buffer.from(svg, "utf8");
}

function warmVignetteSvg(palette: PosterPalette): Buffer {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${POSTER.width}" height="${POSTER.height}">
    <defs>
      <linearGradient id="shade" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0" stop-color="#2d1009" stop-opacity="0.24"/>
        <stop offset="0.42" stop-color="#2d1009" stop-opacity="0.08"/>
        <stop offset="1" stop-color="#2d1009" stop-opacity="0.24"/>
      </linearGradient>
      <radialGradient id="glow" cx="0.72" cy="0.28" r="0.64">
        <stop offset="0" stop-color="#${palette.bgGlow}" stop-opacity="0.28"/>
        <stop offset="1" stop-color="#${palette.bgGlow}" stop-opacity="0"/>
      </radialGradient>
    </defs>
    <rect width="${POSTER.width}" height="${POSTER.height}" fill="url(#glow)"/>
    <rect width="${POSTER.width}" height="${POSTER.height}" fill="url(#shade)"/>
  </svg>`;
  return Buffer.from(svg, "utf8");
}

async function variantBackground(variant: PosterVariant, palette: PosterPalette): Promise<Buffer> {
  const floral = `
    <g opacity="0.32" stroke="#${palette.bannerDeep}" stroke-width="2" fill="none">
      <path d="M884 98 C944 142 990 206 1006 282"/>
      <path d="M930 142 C922 104 952 84 986 92 C982 130 962 148 930 142Z" fill="#${palette.soft}" opacity="0.28"/>
      <path d="M980 238 C942 230 930 196 952 170 C988 184 1000 210 980 238Z" fill="#${palette.soft}" opacity="0.28"/>
      <path d="M92 1176 C158 1118 228 1088 304 1080"/>
      <path d="M160 1128 C122 1124 106 1094 118 1064 C154 1070 174 1092 160 1128Z" fill="#${palette.soft}" opacity="0.28"/>
    </g>`;
  const texture = `
    <g opacity="0.09">
      ${Array.from({ length: 18 }, (_, i) => {
        const y = 60 + i * 72;
        return `<path d="M0 ${y} C180 ${y + 24} 320 ${y - 28} 520 ${y + 8} S860 ${y + 46} 1080 ${y - 6}" stroke="#ffffff" stroke-width="3" fill="none"/>`;
      }).join("")}
    </g>`;
  const sideBand = `
    <path d="M876 0 C1000 178 1010 414 894 592 C776 774 790 1030 958 1350 L1080 1350 L1080 0Z" fill="#${palette.banner}" opacity="0.2"/>`;

  let defs = "";
  let body = "";
  switch (variant.bgStyle) {
    case "cream-botanical":
      defs = `
        <radialGradient id="bg" cx="0.78" cy="0.32" r="0.72">
          <stop offset="0" stop-color="#fff3dd"/>
          <stop offset="1" stop-color="#f6ead2"/>
        </radialGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/><rect x="0" y="0" width="1080" height="1350" fill="#fffaf0" opacity="0.55"/>${floral}`;
      break;
    case "dark-luxe":
      defs = `
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#2d160f"/>
          <stop offset="0.55" stop-color="#5d350e"/>
          <stop offset="1" stop-color="#150b08"/>
        </linearGradient>
        <radialGradient id="lamp" cx="0.68" cy="0.34" r="0.5">
          <stop offset="0" stop-color="#d7a24c" stop-opacity="0.46"/>
          <stop offset="1" stop-color="#d7a24c" stop-opacity="0"/>
        </radialGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/><rect width="1080" height="1350" fill="url(#lamp)"/><rect x="48" y="56" width="984" height="1238" rx="0" fill="none" stroke="#d7a24c" stroke-width="3" opacity="0.28"/>`;
      break;
    case "rose-fashion":
      defs = `
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#ef5d83"/>
          <stop offset="0.55" stop-color="#c2185b"/>
          <stop offset="1" stop-color="#5d0c2a"/>
        </linearGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/><circle cx="128" cy="186" r="170" fill="#ffffff" opacity="0.13"/><circle cx="952" cy="1144" r="230" fill="#ffd1e8" opacity="0.18"/>`;
      break;
    case "blue-gold":
      defs = `
        <linearGradient id="bg" x1="0" y1="0" x2="0.85" y2="1">
          <stop offset="0" stop-color="#02395d"/>
          <stop offset="0.58" stop-color="#026aa3"/>
          <stop offset="1" stop-color="#d8a42d"/>
        </linearGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/><path d="M0 1050 C220 980 382 1048 548 1000 C752 940 882 806 1080 824 L1080 1350 L0 1350Z" fill="#f9a825" opacity="0.32"/>`;
      break;
    case "sale-yellow":
      defs = `
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#ffd94a"/>
          <stop offset="0.5" stop-color="#fb9f2d"/>
          <stop offset="1" stop-color="#c9301c"/>
        </linearGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/>${sideBand}<rect x="-90" y="1032" width="760" height="178" rx="0" fill="#8b0b1f" opacity="0.72" transform="rotate(-5 0 1032)"/>`;
      break;
    default:
      defs = `
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#d86a34"/>
          <stop offset="0.62" stop-color="#b94a25"/>
          <stop offset="1" stop-color="#612716"/>
        </linearGradient>`;
      body = `<rect width="1080" height="1350" fill="url(#bg)"/><rect width="1080" height="1350" fill="#e98a44" opacity="0.26"/>${texture}<rect x="0" y="0" width="1080" height="1350" fill="none" stroke="#f6d6a5" stroke-width="10" opacity="0.14"/>`;
  }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>${defs}</defs>
    ${body}
  </svg>`;
  return sharp(Buffer.from(svg, "utf8")).png().toBuffer();
}

export interface ComposePosterInput {
  plan: {
    palette: string;
    sellingPoints: string[];
    backgroundPrompt: string;
    heroSide: "left" | "right";
    caption: string;
    hashtags: string[];
    engine: string;
  };
  text: PosterText;
  /** EXISTING hero image (product render / product photo) URL or path. */
  heroImageUrl: string;
  /** How many times generation was already retried (caps variation). */
  seed?: number;
  /** Force the procedural gradient even when Pollinations is configured. */
  skipComfy?: boolean;
}

export interface ComposePosterResult {
  buffer: Buffer;
  contentType: "image/jpeg";
  backgroundEngine: string;
  durationMs: number;
  seed: number;
}

/** Background: Pollinations AI when configured, deterministic gradient otherwise. */
async function buildBackground(
  plan: ComposePosterInput["plan"],
  variant: PosterVariant,
  palette: PosterPalette,
  seed: number,
  skipRemote: boolean,
): Promise<{ buffer: Buffer; engine: string; durationMs: number }> {
  if (plan.backgroundPrompt && !skipRemote) {
    const started = Date.now();
    try {
      const out = await generateImageFromText({
        prompt: `${plan.backgroundPrompt}, vibrant Indian ecommerce advertising backdrop, ${variant.bgStyle.replace("-", " ")} mood`,
        width: 1088,
        height: 1344,
        seed,
      });
      return {
        buffer: out.buffer,
        engine: `pollinations:t2i+${variant.name}`,
        durationMs: Date.now() - started,
      };
    } catch (err) {
      console.warn("[promo] Pollinations background failed, using gradient:", (err as Error).message);
    }
  }
  void plan;
  void variant;
  void palette;
  return { buffer: await variantBackground(variant, palette), engine: `local-${variant.name}`, durationMs: 0 };
}

/**
 * Compose one bright promo poster. Throws only when the hero image cannot be
 * fetched (caller falls back to the plain social card path).
 */
export async function composePoster(input: ComposePosterInput): Promise<ComposePosterResult> {
  const variant = posterVariant(input.seed ?? 0);
  const palette = POSTER_PALETTES[variant.palette ?? input.plan.palette] ?? POSTER_PALETTES.BRIGHT_POP;
  const fonts = fontsFor(variant.fontStyle);
  const geo = buildPosterGeometry(input.text);

  const bg = await buildBackground(input.plan, variant, palette, input.seed ?? 0, input.skipComfy === true);

  // HERO — existing render, kept sharp and clean. Poster text is separate.
  const { fetchImageBytes } = await import("@/lib/marketing/storage");
  const heroBytes = (await fetchImageBytes(input.heroImageUrl)).bytes;

  const hero = variant.hero;
  const heroLeft = hero.x;
  const textLeft = variant.textX;
  const heroMasked = await sharp(heroBytes)
    .resize(hero.w, hero.h, { fit: "cover", position: "attention" })
    .modulate({ brightness: 1.07, saturation: 1.22 })
    .sharpen({ sigma: 0.8, m1: 1.25, m2: 2.2 })
    .ensureAlpha()
    .composite([{ input: imageMask(hero.w, hero.h, hero.radius, variant.imageTreatment), blend: "dest-in" }])
    .png()
    .toBuffer();

  // Remote backgrounds arrive at the model's own size — normalize to the
  // canvas so no composite layer exceeds the base (sharp requirement).
  const bgBase = sharp(bg.buffer).resize(POSTER.width, POSTER.height, { fit: "cover" });

  // TEXT LAYER — sharp only, exact strings from the plan/text.
  const points = pointsSvg(input.text.sellingPoints, palette, 440, fonts, variant);
  const offer = offerBlockSvg(input.text, palette, variant.offerStyle, fonts);
  const ctaW = geo.cta.w;
  const ctaH = geo.cta.h;
  const ctaSvg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${ctaW}" height="${ctaH}">
       <rect x="0" y="0" width="${ctaW}" height="${ctaH}" rx="${geo.cta.radius}" fill="#${palette.cta}"/>
       <text x="${ctaW / 2}" y="${Math.round(ctaH / 2 + geo.cta.size * 0.36)}" text-anchor="middle" font-family="${fonts.display}" font-weight="900" font-size="${geo.cta.size}" letter-spacing="2" fill="#${palette.ctaText}">${esc(input.text.cta)}</text>
     </svg>`,
    "utf8",
  );
  const brandSvg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="620" height="150">
       <text x="0" y="76" font-family="${fonts.display}" font-weight="900" font-size="${geo.brand.size}" fill="#${palette.ink}">${esc(input.text.brand)}</text>
       <text x="4" y="114" font-family="${fonts.body}" font-weight="600" font-size="${geo.brand.taglineSize}" letter-spacing="5" fill="#${palette.soft}">${esc(input.text.tagline.toUpperCase())}</text>
     </svg>`,
    "utf8",
  );
  const footerSvg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="980" height="46">
       <text x="0" y="30" font-family="${fonts.body}" font-weight="600" font-size="${geo.footer.size}" fill="#${palette.soft}" opacity="0.95">${esc(input.text.handle)}   •   ${esc(input.text.productLink)}</text>
     </svg>`,
    "utf8",
  );

  const final = await sharp(await bgBase.png().toBuffer())
    .composite([
      { input: warmVignetteSvg(palette), left: 0, top: 0 },
      { input: heroMasked, left: heroLeft, top: hero.y },
      { input: offer, left: textLeft, top: variant.offerY },
      { input: await sharp(points.svg).png().toBuffer(), left: textLeft, top: variant.pointsY },
      { input: ctaSvg, left: textLeft, top: variant.ctaY },
      { input: brandSvg, left: textLeft, top: variant.brandY },
      { input: footerSvg, left: textLeft, top: variant.footerY - 30 },
    ])
    .jpeg({ quality: 96, mozjpeg: false, chromaSubsampling: "4:4:4" })
    .toBuffer();

  return {
    buffer: final,
    contentType: "image/jpeg",
    backgroundEngine: bg.engine,
    durationMs: bg.durationMs,
    seed: input.seed ?? 0,
  };
}

export interface ComposeLuxuryPromoPosterInput {
  productName: string;
  price: number;
  productUrl: string;
  heroImageUrl: string;
  assetImageUrls: string[];
  /** Optional Puter-generated mood/background layer. Real product assets are still overlaid by Sharp. */
  backgroundBuffer?: Buffer;
  seed?: number;
}

export interface ComposeLuxuryPromoPosterResult {
  buffer: Buffer;
  contentType: "image/jpeg";
  engine: string;
  seed: number;
}

type LuxuryTheme = {
  name: string;
  hook: string;
  ink: string;
  soft: string;
  accent: string;
  accent2: string;
  panel: string;
  surface: string;
  border: string;
};

const LUXURY_THEMES: LuxuryTheme[] = [
  {
    name: "warm-heritage",
    hook: "Everyday Grace",
    ink: "f7f1e8",
    soft: "c8b9aa",
    accent: "d6ad72",
    accent2: "c45a5a",
    panel: "171311",
    surface: "2a201c",
    border: "3a2c26",
  },
  {
    name: "minimalist-studio",
    hook: "Handcrafted Comfort",
    ink: "f7f1e8",
    soft: "c8b9aa",
    accent: "e4c38d",
    accent2: "d98a88",
    panel: "171311",
    surface: "342823",
    border: "3a2c26",
  },
  {
    name: "festive-luxury",
    hook: "Timeless Elegance",
    ink: "f7f1e8",
    soft: "d6ad72",
    accent: "d6ad72",
    accent2: "c45a5a",
    panel: "171311",
    surface: "241b17",
    border: "3a2c26",
  },
  {
    name: "earthy-contemporary",
    hook: "Soft Bengali Charm",
    ink: "f7f1e8",
    soft: "c8b9aa",
    accent: "d6ad72",
    accent2: "878a5d",
    panel: "171311",
    surface: "2a201c",
    border: "3a2c26",
  },
];

function luxuryTheme(seed = 0): LuxuryTheme {
  return LUXURY_THEMES[Math.abs(Math.trunc(seed)) % LUXURY_THEMES.length] ?? LUXURY_THEMES[0];
}

function uniqueImages(hero: string, urls: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const url of [hero, ...urls]) {
    const clean = url.trim();
    if (!clean || seen.has(clean)) continue;
    seen.add(clean);
    out.push(clean);
  }
  return out.slice(0, 4);
}

async function luxuryBackground(theme: LuxuryTheme, seed: number): Promise<Buffer> {
  const motif = Array.from({ length: 13 }, (_, i) => {
    const x = (70 + ((i * 151 + seed) % 960));
    const y = (90 + ((i * 227 + seed * 3) % 1160));
    const r = 20 + (i % 4) * 9;
    return `<path d="M${x} ${y} c${r} -${r} ${r * 2} -${r} ${r * 3} 0 c-${r} ${r} -${r * 2} ${r} -${r * 3} 0z" fill="#${theme.accent}" opacity="0.055"/>`;
  }).join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#211916"/>
        <stop offset="0.52" stop-color="#171311"/>
        <stop offset="1" stop-color="#0f0c0a"/>
      </linearGradient>
      <radialGradient id="glow" cx="0.74" cy="0.23" r="0.62">
        <stop offset="0" stop-color="#${theme.accent2}" stop-opacity="0.18"/>
        <stop offset="1" stop-color="#${theme.accent}" stop-opacity="0"/>
      </radialGradient>
      <linearGradient id="terracotta" x1="0" y1="0" x2="0.8" y2="1">
        <stop offset="0" stop-color="#c45a5a" stop-opacity="0.16"/>
        <stop offset="1" stop-color="#d6ad72" stop-opacity="0"/>
      </linearGradient>
    </defs>
    <rect width="1080" height="1350" fill="url(#bg)"/>
    <rect width="1080" height="1350" fill="url(#glow)"/>
    <rect width="1080" height="1350" fill="url(#terracotta)"/>
    ${motif}
    <g opacity="0.07">
      ${Array.from({ length: 18 }, (_, i) => `<path d="M0 ${80 + i * 72} C220 ${112 + i * 72} 410 ${44 + i * 72} 650 ${88 + i * 72} S930 ${132 + i * 72} 1080 ${80 + i * 72}" stroke="#f7f1e8" stroke-width="2" fill="none"/>`).join("")}
    </g>
    <rect x="32" y="32" width="1016" height="1286" rx="48" fill="none" stroke="#${theme.border}" stroke-width="2"/>
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

async function framedImage(url: string, width: number, height: number, radius: number, theme: LuxuryTheme): Promise<Buffer> {
  const { bytes } = await import("@/lib/marketing/storage").then((m) => m.fetchImageBytes(url));
  const mask = imageMask(width, height, radius, "panel");
  const image = await sharp(bytes)
    .resize(width, height, { fit: "cover", position: "attention" })
    .modulate({ brightness: 1.04, saturation: 1.12 })
    .sharpen({ sigma: 0.6, m1: 1.1, m2: 1.8 })
    .ensureAlpha()
    .composite([{ input: mask, blend: "dest-in" }])
    .png()
    .toBuffer();
  const frame = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width + 24}" height="${height + 24}">
    <defs><filter id="shadow"><feDropShadow dx="0" dy="16" stdDeviation="13" flood-color="#000000" flood-opacity="0.38"/></filter></defs>
    <rect x="3" y="3" width="${width + 18}" height="${height + 18}" rx="${radius + 10}" fill="#${theme.accent}" opacity="0.2" filter="url(#shadow)"/>
    <rect x="12" y="12" width="${width}" height="${height}" rx="${radius}" fill="#${theme.surface}" stroke="#${theme.accent}" stroke-width="4" opacity="0.96"/>
  </svg>`);
  return sharp(frame)
    .composite([{ input: image, left: 12, top: 12 }])
    .png()
    .toBuffer();
}

function wrapWords(text: string, maxChars: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const word of words) {
    const next = cur ? `${cur} ${word}` : word;
    if (next.length <= maxChars || !cur) {
      cur = next;
    } else {
      lines.push(cur);
      cur = word;
    }
    if (lines.length >= maxLines) break;
  }
  if (cur && lines.length < maxLines) lines.push(cur);
  return lines;
}

function luxuryTextLayer(input: ComposeLuxuryPromoPosterInput, theme: LuxuryTheme): Buffer {
  const titleLines = wrapWords(input.productName, 24, 3);
  const title = titleLines
    .map((line, i) => `<text x="72" y="${332 + i * 38}" font-family="Inter, Arial, sans-serif" font-size="29" font-weight="750" fill="#${theme.ink}">${esc(line)}</text>`)
    .join("");
  const hookLines = wrapWords(theme.hook, 12, 2)
    .map((line, i) => `<text x="70" y="${184 + i * 74}" font-family="Playfair Display, Georgia, 'Times New Roman', serif" font-size="72" font-weight="700" fill="#${theme.ink}" filter="url(#softShadow)">${esc(line)}</text>`)
    .join("");
  const displayUrl = "thetanti.shop";
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>
      <filter id="softShadow"><feDropShadow dx="0" dy="10" stdDeviation="8" flood-color="#000" flood-opacity="0.32"/></filter>
      <linearGradient id="price" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#${theme.accent2}"/>
        <stop offset="1" stop-color="#${theme.accent}"/>
      </linearGradient>
    </defs>
    <text x="70" y="116" font-family="Inter, Arial, sans-serif" font-size="20" font-weight="850" letter-spacing="7" fill="#${theme.accent}" opacity="0.98">THE TANTI</text>
    ${hookLines}
    ${title}
    <g transform="translate(70 486)" filter="url(#softShadow)">
      <rect x="0" y="0" width="326" height="118" rx="20" fill="url(#price)"/>
      <text x="32" y="76" font-family="Inter, Arial, sans-serif" font-size="54" font-weight="900" fill="#fffdf5">₹${input.price}</text>
      <text x="194" y="74" font-family="Inter, Arial, sans-serif" font-size="25" font-weight="900" letter-spacing="3" fill="#fffdf5">FLAT</text>
    </g>
    <text x="72" y="662" font-family="Inter, Arial, sans-serif" font-size="23" font-weight="700" fill="#${theme.soft}">Premium-look sarees. One simple price.</text>
    <g transform="translate(70 1128)">
      <rect x="0" y="0" width="268" height="70" rx="35" fill="#${theme.ink}" opacity="0.96"/>
      <text x="134" y="45" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="25" font-weight="900" letter-spacing="1.5" fill="#${theme.panel}">SHOP NOW</text>
    </g>
    <text x="70" y="1278" font-family="Inter, Arial, sans-serif" font-size="23" font-weight="700" fill="#${theme.ink}">${esc(SITE.name)}</text>
    <text x="198" y="1278" font-family="Inter, Arial, sans-serif" font-size="21" font-weight="650" fill="#${theme.soft}">• ${esc(displayUrl)}</text>
  </svg>`;
  return Buffer.from(svg);
}

type EditorialPosterStyle = {
  hook: string;
  tagline: string;
  cta: string;
  displayFont: string;
  bodyFont: string;
  layout: 0 | 1 | 2;
};

function editorialPosterStyle(seed: number, theme: LuxuryTheme): EditorialPosterStyle {
  const hooks = [
    theme.hook,
    "Timeless, By Design",
    "The Saree Edit",
    "Grace In Every Drape",
    "Rooted In Bengal",
    "Soft Festive Ease",
    "Everyday Elegance",
  ];
  const taglines = [
    "SAREES FOR REAL LIFE",
    "BENGALI SAREE STYLING",
    "READY TO WEAR, READY TO LOVE",
    "ONE PRICE. MANY MOMENTS.",
    "WOVEN FOR EVERYDAY BEAUTY",
  ];
  const ctas = ["SHOP NOW", "ORDER NOW", "DISCOVER", "SHOP THE LOOK"];
  const fonts = [
    { displayFont: "Playfair Display, Georgia, 'Times New Roman', serif", bodyFont: "Inter, Arial, sans-serif" },
    { displayFont: "Cormorant Garamond, Garamond, Georgia, serif", bodyFont: "'Segoe UI', Arial, sans-serif" },
    { displayFont: "Bodoni 72, Didot, Georgia, serif", bodyFont: "Trebuchet MS, 'Segoe UI', sans-serif" },
    { displayFont: "Georgia, 'Times New Roman', serif", bodyFont: "Arial, 'Helvetica Neue', sans-serif" },
  ];
  const safeSeed = Math.abs(Math.trunc(seed));
  const font = fonts[safeSeed % fonts.length] ?? fonts[0];
  return {
    hook: hooks[(safeSeed * 3 + 1) % hooks.length] ?? theme.hook,
    tagline: taglines[(safeSeed * 5 + 2) % taglines.length] ?? taglines[0],
    cta: ctas[(safeSeed * 7 + 3) % ctas.length] ?? ctas[0],
    displayFont: font.displayFont,
    bodyFont: font.bodyFont,
    layout: (safeSeed % 3) as 0 | 1 | 2,
  };
}

async function editorialCampaignBase(source: Buffer, theme: LuxuryTheme): Promise<Buffer> {
  const base = await sharp(source)
    .resize(CANVAS.width, CANVAS.height, { fit: "cover", position: "attention" })
    .modulate({ brightness: 0.96, saturation: 1.05 })
    .sharpen({ sigma: 0.55, m1: 0.9, m2: 1.55 })
    .png()
    .toBuffer();
  const grading = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>
      <linearGradient id="leftShade" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0" stop-color="#171311" stop-opacity="0.76"/>
        <stop offset="0.36" stop-color="#171311" stop-opacity="0.44"/>
        <stop offset="0.62" stop-color="#171311" stop-opacity="0.10"/>
        <stop offset="1" stop-color="#171311" stop-opacity="0.00"/>
      </linearGradient>
      <linearGradient id="bottomShade" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#171311" stop-opacity="0.00"/>
        <stop offset="0.64" stop-color="#171311" stop-opacity="0.18"/>
        <stop offset="1" stop-color="#171311" stop-opacity="0.70"/>
      </linearGradient>
      <radialGradient id="warmGlow" cx="0.24" cy="0.18" r="0.76">
        <stop offset="0" stop-color="#${theme.accent}" stop-opacity="0.12"/>
        <stop offset="1" stop-color="#${theme.accent}" stop-opacity="0"/>
      </radialGradient>
    </defs>
    <rect width="${CANVAS.width}" height="${CANVAS.height}" fill="url(#warmGlow)"/>
    <rect width="${CANVAS.width}" height="${CANVAS.height}" fill="url(#leftShade)"/>
    <rect width="${CANVAS.width}" height="${CANVAS.height}" fill="url(#bottomShade)"/>
    <rect x="28" y="28" width="${CANVAS.width - 56}" height="${CANVAS.height - 56}" fill="none" stroke="#${theme.ink}" stroke-width="2" opacity="0.18"/>
  </svg>`);
  return sharp(base).composite([{ input: grading, left: 0, top: 0 }]).png().toBuffer();
}

function editorialCampaignTextLayer(
  input: ComposeLuxuryPromoPosterInput,
  theme: LuxuryTheme,
  posterStyle: EditorialPosterStyle,
): Buffer {
  const productLines = wrapWords(input.productName, 25, 2);
  const layout = posterStyle.layout;
  const x = layout === 1 ? 78 : 70;
  const brandY = layout === 2 ? 96 : 104;
  const tagY = layout === 2 ? 1012 : 178;
  const hookY = layout === 1 ? 272 : layout === 2 ? 1080 : 300;
  const productY = layout === 1 ? 528 : layout === 2 ? 642 : 562;
  const priceY = layout === 1 ? 656 : layout === 2 ? 762 : 666;
  const bodyY = layout === 1 ? 824 : layout === 2 ? 938 : 838;
  const ctaY = layout === 1 ? 1116 : layout === 2 ? 1180 : 1110;
  const productTitle = productLines
    .map(
      (line, i) =>
        `<text x="${x + 2}" y="${productY + i * 38}" font-family="${posterStyle.bodyFont}" font-size="30" font-weight="750" fill="#${theme.ink}">${esc(line)}</text>`,
    )
    .join("");
  const hookLines = wrapWords(posterStyle.hook, layout === 2 ? 16 : 13, 2)
    .map(
      (line, i) =>
        `<text x="${x}" y="${hookY + i * 82}" font-family="${posterStyle.displayFont}" font-size="${layout === 2 ? 68 : 78}" font-weight="700" fill="#${theme.ink}" filter="url(#shadow)">${esc(line)}</text>`,
    )
    .join("");
  const price = `₹${input.price}`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>
      <filter id="shadow"><feDropShadow dx="0" dy="10" stdDeviation="8" flood-color="#000000" flood-opacity="0.42"/></filter>
      <filter id="smallShadow"><feDropShadow dx="0" dy="7" stdDeviation="5" flood-color="#000000" flood-opacity="0.32"/></filter>
      <linearGradient id="badge" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#${theme.accent2}"/>
        <stop offset="1" stop-color="#${theme.accent}"/>
      </linearGradient>
    </defs>
    <text x="${x}" y="${brandY}" font-family="${posterStyle.bodyFont}" font-size="19" font-weight="850" letter-spacing="7" fill="#${theme.accent}" opacity="0.98">THE TANTI</text>
    <line x1="${x}" y1="${brandY + 28}" x2="${x + 174}" y2="${brandY + 28}" stroke="#${theme.accent}" stroke-width="2" opacity="0.72"/>
    <text x="${x}" y="${tagY}" font-family="${posterStyle.bodyFont}" font-size="18" font-weight="750" letter-spacing="4" fill="#${theme.soft}" opacity="0.96">${esc(posterStyle.tagline)}</text>
    ${hookLines}
    <text x="${x + 2}" y="${productY - 48}" font-family="${posterStyle.bodyFont}" font-size="21" font-weight="850" letter-spacing="5" fill="#${theme.accent}">FEATURED SAREE</text>
    ${productTitle}
    <g transform="translate(${x} ${priceY})" filter="url(#smallShadow)">
      <rect x="0" y="0" width="318" height="110" rx="55" fill="url(#badge)" opacity="0.96"/>
      <text x="36" y="72" font-family="${posterStyle.bodyFont}" font-size="54" font-weight="950" fill="#fffdf5">${esc(price)}</text>
      <text x="192" y="70" font-family="${posterStyle.bodyFont}" font-size="23" font-weight="950" letter-spacing="3.5" fill="#fffdf5">FLAT</text>
    </g>
    <text x="${x + 2}" y="${bodyY}" font-family="${posterStyle.bodyFont}" font-size="24" font-weight="700" fill="#${theme.ink}" filter="url(#shadow)">Premium Bengali saree style at one simple price.</text>
    <g transform="translate(${x} ${ctaY})" filter="url(#smallShadow)">
      <rect x="0" y="0" width="286" height="68" rx="34" fill="#${theme.ink}" opacity="0.96"/>
      <text x="143" y="44" text-anchor="middle" font-family="${posterStyle.bodyFont}" font-size="24" font-weight="950" letter-spacing="1.6" fill="#${theme.panel}">${esc(posterStyle.cta)}</text>
    </g>
    <text x="${x}" y="1266" font-family="${posterStyle.bodyFont}" font-size="22" font-weight="800" fill="#${theme.ink}">${esc(SITE.name)}</text>
    <text x="${x + 126}" y="1266" font-family="${posterStyle.bodyFont}" font-size="20" font-weight="650" fill="#${theme.soft}">• thetanti.shop</text>
  </svg>`;
  return Buffer.from(svg);
}

export async function composeLuxuryPromoPoster(
  input: ComposeLuxuryPromoPosterInput,
): Promise<ComposeLuxuryPromoPosterResult> {
  const seed = input.seed ?? 0;
  const theme = luxuryTheme(seed);

  if (input.backgroundBuffer) {
    const posterStyle = editorialPosterStyle(seed, theme);
    const base = await editorialCampaignBase(input.backgroundBuffer, theme);
    const final = await sharp(base)
      .composite([{ input: editorialCampaignTextLayer(input, theme, posterStyle), left: 0, top: 0 }])
      .jpeg({ quality: 96, mozjpeg: false, chromaSubsampling: "4:4:4" })
      .toBuffer();

    return {
      buffer: final,
      contentType: "image/jpeg",
      engine: `sharp-editorial-campaign:${theme.name}:layout-${posterStyle.layout}`,
      seed,
    };
  }

  const images = uniqueImages(input.heroImageUrl, input.assetImageUrls);
  const hero = images[0] ?? input.heroImageUrl;
  const detail = images[1] ?? hero;
  const third = images[2] ?? detail;

  const [bg, heroPanel, detailPanel, thirdPanel] = await Promise.all([
    luxuryBackground(theme, seed),
    framedImage(hero, 452, 812, 28, theme),
    framedImage(detail, 332, 236, 22, theme),
    framedImage(third, 270, 196, 20, theme),
  ]);

  const glow = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS.width}" height="${CANVAS.height}">
    <defs>
      <linearGradient id="left" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0" stop-color="#000000" stop-opacity="0.46"/>
        <stop offset="0.48" stop-color="#000000" stop-opacity="0.16"/>
        <stop offset="1" stop-color="#000000" stop-opacity="0"/>
      </linearGradient>
    </defs>
    <rect width="1080" height="1350" fill="url(#left)"/>
    <circle cx="812" cy="250" r="350" fill="#${theme.accent}" opacity="0.12"/>
  </svg>`);

  const final = await sharp(bg)
    .resize(CANVAS.width, CANVAS.height, { fit: "cover" })
    .composite([
      { input: glow, left: 0, top: 0 },
      { input: heroPanel, left: 570, top: 162 },
      { input: detailPanel, left: 70, top: 760 },
      { input: thirdPanel, left: 378, top: 984 },
      { input: luxuryTextLayer(input, theme), left: 0, top: 0 },
    ])
    .jpeg({ quality: 96, mozjpeg: false, chromaSubsampling: "4:4:4" })
    .toBuffer();

  return { buffer: final, contentType: "image/jpeg", engine: `sharp-luxury-collage:${theme.name}`, seed };
}

/** Procedural bright gradient (used when ComfyUI is off or failed). */
async function gradientFallback(plan: ComposePosterInput["plan"]): Promise<Buffer> {
  const palette = POSTER_PALETTES[plan.palette] ?? POSTER_PALETTES.BRIGHT_POP;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${POSTER.width}" height="${POSTER.height}">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="0.6" y2="1">
        <stop offset="0" stop-color="#${palette.bgTop}"/>
        <stop offset="1" stop-color="#${palette.bgBottom}"/>
      </linearGradient>
      <radialGradient id="glow" cx="0.78" cy="0.42" r="0.6">
        <stop offset="0" stop-color="#${palette.bgGlow}" stop-opacity="0.85"/>
        <stop offset="1" stop-color="#${palette.bgGlow}" stop-opacity="0"/>
      </radialGradient>
    </defs>
    <rect width="${POSTER.width}" height="${POSTER.height}" fill="url(#bg)"/>
    <rect width="${POSTER.width}" height="${POSTER.height}" fill="url(#glow)"/>
  </svg>`;
  return sharp(Buffer.from(svg, "utf8")).png().toBuffer();
}
