/**
 * Social Director — PURE logic for the organic Facebook/Instagram post flow.
 *
 *   draft → pending_approval → approved → published   (draft|pending → rejected)
 *
 * Content is generated by LOCAL Ollama only (lib/marketing/ollama.ts) from the
 * product's EXISTING images (no Qwen Image Edit calls here — those stay in the
 * paid product-photo pipeline). One primary image per post; the caption is
 * composed deterministically from parsed fields so Meta always gets clean,
 * approved text. Pure functions only — engine + route code live elsewhere.
 */
import { SITE } from "@/lib/site";

export type SocialState = "draft" | "pending_approval" | "approved" | "published" | "rejected";

export const SOCIAL_STATES: SocialState[] = [
  "draft",
  "pending_approval",
  "approved",
  "published",
  "rejected",
];

export const SOCIAL_STATE_LABEL: Record<SocialState, string> = {
  draft: "Draft",
  pending_approval: "Pending approval",
  approved: "Approved",
  published: "Published",
  rejected: "Rejected",
};

/** Which states may transition forward to `to` (rejections allowed from draft/pending). */
export function canTransitionSocial(from: SocialState, to: SocialState): boolean {
  switch (to) {
    case "pending_approval":
      return from === "draft";
    case "approved":
      return from === "pending_approval";
    case "published":
      return from === "approved";
    case "rejected":
      return from === "draft" || from === "pending_approval";
    case "draft":
      return from === "pending_approval"; // edit cycle
    default:
      return false;
  }
}

/** A queued social post as stored in social_posts / demo db. */
export interface SocialPostRecord {
  id: string;
  /** Idempotency key — one post per product + kind; retries reuse it. */
  key: string;
  productSlug: string;
  productName: string;
  productPrice: number;
  productCategory: string;
  /** The EXISTING product image used for this post (never a new generation). */
  imageUrl: string;
  /** Branded 4:5 card (photo + cream copy panel) composed from imageUrl.
   *  Undefined when composition fell back to the raw product image. */
  postImageUrl?: string;
  /** Public HTTPS URL (Supabase) used for Meta media — resolved at publish. */
  publicImageUrl?: string;
  kind: SocialPostKind;
  language: SocialLanguage;
  caption: SocialCaption;
  engine: string;
  state: SocialState;
  createdAt: string;
  updatedAt: string;
  generatedAt?: string;
  approvedAt?: string;
  publishedAt?: string;
  rejectedReason?: string;
  /** Meta ids after publishing (idempotent retries reuse these). */
  fbPostId?: string;
  igMediaId?: string;
  fbPhotoId?: string;
  igImageId?: string;
  publishError?: string;
}

export type SocialPostKind =
  | "product_feature"
  | "behind_the_loom"
  | "styling_tip"
  | "festive_pick"
  | "promo_poster"
  | "ai_model_ad";
export type SocialLanguage = "hinglish" | "banglish";

export const SOCIAL_KINDS: SocialPostKind[] = [
  "product_feature",
  "behind_the_loom",
  "styling_tip",
  "festive_pick",
  "promo_poster",
  "ai_model_ad",
];

export const SOCIAL_KIND_LABEL: Record<SocialPostKind, string> = {
  product_feature: "Product feature",
  behind_the_loom: "Behind the loom",
  styling_tip: "Styling tip",
  festive_pick: "Festive pick",
  promo_poster: "Promo poster (₹199)",
  ai_model_ad: "AI model ad (Pollinations)",
};

export const SOCIAL_LANGUAGES: SocialLanguage[] = ["hinglish", "banglish"];

export interface SocialCaption {
  hook: string;
  body: string;
  cta: string;
  hashtags: string[];
}

/* --------------------------------- prompts --------------------------------- */

/** Tone contract shared by every social generation (matches lib/site brand). */
export function socialSystemPrompt(): string {
  return [
    `You are the Content Director for ${SITE.name}, an Indian saree webstore where every saree costs a flat ₹199.`,
    "Audience: Indian women aged 30-55 and adult children buying budget-friendly gifts.",
    "Tone: homely, warm, respectful, family-oriented. Short spoken-style sentences.",
    "Never invent fabric names, certifications, origin claims, discounts, delivery dates or product specs beyond what is given.",
    "Never use fake urgency ('last chance', 'hurry, only 2 left') or exaggerated claims.",
    "You write Facebook and Instagram organic post captions.",
  ].join(" ");
}

export interface SocialPromptInput {
  productName: string;
  productCategory: string;
  price: number;
  fabric?: string;
  productUrl: string;
  kind: SocialPostKind;
  language: SocialLanguage;
}

export function socialUserPrompt(input: SocialPromptInput): string {
  const fabric = input.fabric?.trim() || "soft breathable fabric";
  const kindNote: Record<SocialPostKind, string> = {
    product_feature: "A warm product feature post introducing the saree.",
    behind_the_loom:
      "A behind-the-scenes post about the weaving/craft tradition behind this saree style. Do NOT invent weaver names, villages or workshop details.",
    styling_tip:
      "A short styling tip post showing one way to drape/accessorise this saree for daily wear.",
    festive_pick:
      "A gentle festive/occasion suggestion post for this saree (no festival-date claims).",
    promo_poster:
      "A bright campaign poster caption announcing the flat-price offer. Keep it energetic and honest; the poster itself carries the price.",
    ai_model_ad:
      "A caption for the AI model-ad creative. The image itself carries the price banner — keep the caption warm and short, no price repetition needed beyond the flat ₹ price fact.",
  };
  const langNote: Record<SocialLanguage, string> = {
    hinglish:
      "Conversational Hinglish (Hindi words in Latin script mixed with English), e.g. 'aapke', 'roz', 'aaram se'.",
    banglish:
      "Conversational Banglish (Bengali words in Latin script mixed with English), e.g. 'apnar', 'khub', 'sohoj'.",
  };
  return [
    `Saree: ${input.productName}. Category: ${input.productCategory.replace(/-/g, " ")}. Fabric: ${fabric}. Price: ₹${input.price} (flat, never changes).`,
    `Product page: ${input.productUrl}`,
    `Post type: ${kindNote[input.kind]}`,
    `Language style: ${langNote[input.language]}`,
    "Use the product page URL verbatim inside cta.",
    "Return ONLY minified JSON with this exact shape (no markdown, no commentary):",
    '{"hook":"one scroll-stopping first line under 80 characters","body":"2-4 short sentences about the saree, warm and honest","cta":"call to action including the product page URL verbatim","hashtags":["exactly 6 hashtags starting with #"]}',
  ].join("\n");
}

/* --------------------------------- parsing --------------------------------- */

/**
 * Parse a model reply into a caption. Throws on malformed/incomplete output so
 * the engine can fall back to the template instead of publishing junk.
 */
export function parseSocialReply(text: string): SocialCaption {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end <= start) throw new Error("Social model returned no JSON object");
  const raw = JSON.parse(text.slice(start, end + 1)) as Record<string, unknown>;

  const hook = String(raw.hook ?? "").trim();
  const body = String(raw.body ?? "").trim();
  const cta = String(raw.cta ?? "").trim();
  const hashtags = (Array.isArray(raw.hashtags) ? raw.hashtags : [])
    .map((h) => {
      const s = String(h).trim();
      return s ? (s.startsWith("#") ? s : `#${s.replace(/^#+/, "")}`) : "";
    })
    .filter(Boolean)
    .slice(0, 6);

  if (!hook || hook.length > 120) throw new Error("Social reply: hook missing or too long");
  if (!body || body.length > 600) throw new Error("Social reply: body missing or too long");
  if (!cta) throw new Error("Social reply: cta missing");
  if (hashtags.length < 3) throw new Error("Social reply: too few hashtags");

  return { hook, body, cta, hashtags };
}

/** Deterministic template caption — used when Ollama is unavailable. */
export function fallbackSocialCaption(input: SocialPromptInput): SocialCaption {
  const fabric = input.fabric?.trim() || "soft fabric";
  if (input.language === "banglish") {
    return {
      hook: `${input.productName} — khub comfort, only ₹${input.price}`,
      body: `Soft ${fabric.toLowerCase()} saree for daily wear. Sohoj drape, breathable weave — poore din aaram.`,
      cta: `Apnar saree order korun: ${input.productUrl}`,
      hashtags: ["#SareeLove", "#DailyWearSaree", "#Saree199", "#TheTanti", "#HandloomSaree", "#SareeStyle"],
    };
  }
  return {
    hook: `${input.productName} — sirf ₹${input.price}`,
    body: `Soft ${fabric.toLowerCase()} saree for daily wear. Aaram se drape ho jaata hai, poore din comfortable.`,
    cta: `Order kariye: ${input.productUrl}`,
    hashtags: ["#SareeLove", "#DailyWearSaree", "#Saree199", "#TheTanti", "#HandloomSaree", "#SareeStyle"],
  };
}

/* ------------------------------ caption output ------------------------------ */

/** Full caption string for Meta publishing (deterministic composition). */
export function socialToCaption(caption: SocialCaption): string {
  return [
    caption.hook,
    "",
    caption.body,
    "",
    caption.cta,
    "",
    caption.hashtags.join(" "),
  ].join("\n");
}

/* --------------------------------- helpers --------------------------------- */

/** Idempotency key: one post per product+kind+language. */
export function socialKey(
  productSlug: string,
  kind: SocialPostKind,
  language: SocialLanguage,
): string {
  return `${productSlug}:${kind}:${language}`;
}

/** First usable product image (fallback chain caller supplies). */
export function pickSocialImage(images: string[]): string | undefined {
  return images.find((u) => typeof u === "string" && u.trim().length > 0);
}

/**
 * TEST MODE guard — publishing actions are simulated and clearly marked.
 * Enable with SOCIAL_TEST_MODE=true (default true so nothing goes live by
 * accident on a fresh install).
 */
export function isSocialTestMode(): boolean {
  const raw = process.env.SOCIAL_TEST_MODE?.trim().toLowerCase();
  if (raw === undefined || raw === "") return true;
  return raw === "true" || raw === "1";
}
